;;; Automatically generated by `recentf' on Mon Nov 28 11:07:21 2011.

(setq recentf-list
      '(
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/config/routes.rb"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/public/javascripts/orders_controller.js"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/app/controllers/orders_controller.rb"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/app/views/orders/_payment_details.html.haml"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/app/views/orders/new.html.haml"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/public/javascripts/ie9.js"
        "/Users/mdesjardins/Library/Preferences/Aquamacs Emacs/Preferences.el"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/public/javascripts/restaurant.js"
        "/Users/mdesjardins/.ido.last"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/app/controllers/restaurants_controller.rb"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/app/models/restaurant.rb"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/app/views/shared/_slot_slider.html.haml"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/public/javascripts/timeslots.js"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/app/views/reservations/_reservations.html.haml"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/app/helpers/order_helper.rb"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/app/views/orders/invite_on_facebook.html.haml"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/app/models/order.rb"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/lib/payment/gateway_transactions.rb"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/config/application.rb"
        "/Users/mdesjardins/_work/elctech/src/cityeats-web/app/views/orders/iframe.html.haml"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
