;;; Automatically generated by `recentf' on Mon Mar  4 08:43:53 2013.

(setq recentf-list
      '(
        "/Users/mdesjardins/Library/Preferences/Aquamacs Emacs/Preferences.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
